name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
#    - name: Check for Lints
#      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
    - name: Generate Documentation
      run: cargo doc --verbose
